### ISSUE TITLE
Rerun only for certain errors?

### ISSUE THREAD

**Issue by deeplook** [pytest-dev/pytest-rerunfailures#101]
I've discovered this pytest plugin, which looks very interesting to me, but ideally I would want it to rerun tests a little more fine-grained, namely only when specific errors are detected, say HTTP response codes 5xx. I don't think this is already possible, right? If not maybe consider it as a feature request?

**Comment by icemac** [comment]
It is not yet possible to rerun on specific exceptions. Maybe you would like to come up with a pull request.

**Comment by gnikonorov** [comment]
Hey @icemac @deeplook what were we thinking? How about to start a flag that is a comma separated string of exception names ( e.g: `--only-rerun=ValueError,BufferError,MyCustomError` )

**Comment by gnikonorov** [comment]
Hey @icemac I self assigned this to myself since I want to make a PR for this. My apologies if this was unwelcome

**Comment by icemac** [comment]
@gnikonorov This is perfectly welcome. I was no planning to work on this issue. Thank you for tackling it.
