### ISSUE TITLE
collision with @pytest.mark.incremental

### ISSUE THREAD

**Issue by EpicNuts** [pytest-dev/pytest-rerunfailures#102]
I have a class with 3 tests in it. 
The class has an incremental mark, so that if the first test fails, the subsequent tests are failed as 'XFAIL', or expected fail instead of being run. This is very useful when the tests are used as steps to setup a specific state, as it allows to fail-fast and move on.
The problem I'm seeing is, the 3rd test has failed, and so is rerun. However the rerun test is automaically marked as XFAIL.

```
@pytest.mark.incremental
class Test_03_TestAThing(InitSetUp, test_steps):

    def setUp(self):
        defaultSetup(self)

    def test_01(self): 
        self.test_it()
    
    def test_02(self): 
        self.test_it_again()
   
    @pytest.mark.flaky(rerun=1)
    def test_03(self): 
        self.fail()
```

```
tests/Test_03_TestAThing::test_01 PASSED               [ 36%]
tests/Test_03_TestAThing::test_02 PASSED               [ 37%]
tests/Test_03_TestAThing::test_03 RERUN                [ 38%]
tests/Test_03_TestAThing::test_03 XFAIL                   [ 38%]
```

I'm not sure the best way to handle this, but If the .mark.flaky could be applied to the class level, maybe running the whole test class again would be a better option than rerunning a specific test that relies on a state created by previous tests?

**Comment by icemac** [comment]
Which plug-in provides `pytest.mark.incremental`?

**Comment by EpicNuts** [comment]
> Which plug-in provides `pytest.mark.incremental`?

I'm not sure it is a plug-in, as pytest uses it as an example in the simple docs:
https://docs.pytest.org/en/latest/example/simple.html#incremental-testing-test-steps

**Comment by icemac** [comment]
I see. So maybe it is better to move `@pytest.mark.flaky` to the test class.
Does that work for you?

**Comment by EpicNuts** [comment]
Yep, that's probably the best bet. I'm trying better control the individual tests and having a great tool like this is really helpful, so thanks for your work! :)
