### ISSUE TITLE
Allow fixtures or tests to request a rerun

### ISSUE THREAD

**Issue by xmo-odoo** [pytest-dev/pytest-rerunfailures#112]
rerunfailures is nice but it's very "static". I've got a use case where I call into an external API (either as part of the test setup or as part of the test), and that API can go down or be rate-limited, in which case I want to delay the rerun until I'm reasonably sure the API will be up again, however rerunfailures only allows for hard-coded (or global options-based) delays currently.

I've tried looking at the doc' and code, but haven't seen anything which would allow fixtures or test to say "rerun me at <time>" or "rerun me in <time>" (possibly under the assumption that rerunfailures is enabled and it'd fail immediately with a `--reruns` of 0)

**Comment by The-Compiler** [comment]
I suppose #101 would help with this as well? Then you could e.g. say that tests raising `ExternalAPIError` should be rerun, and sleep before raising it inside your fixture?

**Comment by xmo-odoo** [comment]
Technically I can already sleep-and-raise any error I want so kind-of?

**Comment by gnikonorov** [comment]
@xmo-odoo - if I understand correctly, wouldn't [this](https://github.com/pytest-dev/pytest-rerunfailures#re-run-individual-failures) solve your problem? You could apply this to individual tests and you could set `reruns_delay` to the number of seconds you want to sleep in between reruns.

Alternatively, you could do what @The-Compiler suggested about and do something like `pytest --reruns 5 --only-rerun MyAPIError --only-rerun MyOtherAPIError --reruns-delay 1`.

Let me know if I misundestood

**Comment by xmo-odoo** [comment]
@gnikonorov the problem of this is that the test can't specify a rerun delay. See the original use-case: this is a test which makes use of a rate-limited API, said API is specifically rate-limited on an hourly basis, so once the rate limit is hit it might be necessary to wait for 10 or 15mn until the reset depending how fast we burned through the rate limit (which is mostly though not only a function of the xdist concurrency).

**Comment by gnikonorov** [comment]
@xmo-odoo I see, thanks for explaining.

So basically, you’d want to pause test suite execution until the API is available again, then resume execution and you’d want to specify this as a rule along the lines of ‘if this error happens then rerun me at the start of hour’ ( just an example, I’m not saying that’s a solution ).

**Comment by xmo-odoo** [comment]
@gnikonorov Pretty much yeah. I'm aware this is not quite why this plugin exists and this is only adjacent so I'm completely OK closing as out of scope, but assuming it can get the failure information I figured it could be a relatively easy addition and not *too far* away from the core purpose.

**Comment by gnikonorov** [comment]
That’s beyond me to answer, since I recently started contributing to this repo. Perhaps @icemac or @sallner will be better able to answer that question

**Comment by sallner** [comment]
@xmo-odoo My opinion on this issue is, that this plugin is deliberately static and simply in its usage. Your use case seems totally valid and also occurred in one of my projects. But this seems quite a large overhead to be maintained in this plugin now. 

One thing, I could image though, is to implement the feature in https://github.com/pytest-dev/pytest-rerunfailures/pull/113 also as option too the flaky marker. As we typically allow all options to be overridden within the decorator call. This would allow you to raise an (maybe application specific) error in your testcase or fixture and then specify the delay at the @flaky decorator together with the error. 

Does that sound like possible solution?

**Comment by xmo-odoo** [comment]
@sallner it could work but I think for a dynamic delay I'd need one more thing: that the reruns delay be fetched after the failure (just before sleeping it off).

This way I could hook into the run and update the delay on the mark after a failure. In fact, I might not even need #113, I would just update the delay to whatever I want if the marker exception is raised, otherwise reset it to the default delay (to avoid a delay of 10mn when it's an assertion error which has no reason to wait for instance).

**Comment by gnikonorov** [comment]
This sounds like a good candidate for a separate plugin IMO since it's not really a flaky test so much as a guaranteed failure for some dynamic amount of time due to a rate limiting API 

I think [this link](http://plugincompat.herokuapp.com/) should list all pytest compatible plugins ( taken from [here](https://github.com/pytest-dev/plugincompat) if you're interested ). If one doesn't exist, I've been wanting to write a plugin, so I think I may try to tackle this.

**Comment by xmo-odoo** [comment]
> This sounds like a good candidate for a separate plugin IMO since it's not really a flaky test so much as a guaranteed failure for some dynamic amount of time due to a rate limiting API

That's definitely true from a functional standpoint, but I feel like there's a 95% overlap with rerunfailures at the technical level.

**Comment by gnikonorov** [comment]
> > This sounds like a good candidate for a separate plugin IMO since it's not really a flaky test so much as a guaranteed failure for some dynamic amount of time due to a rate limiting API
> 
> 
> 
> That's definitely true from a functional standpoint, but I feel like there's a 95% overlap with rerunfailures at the technical level.

I agree about the overlap, but I feel the functionality is different, so we should still split this into a different plugin since it describes a different use case to someone not aware of the implementation details. But still, will defer to @sallner as he has more insight than me.

**Comment by sallner** [comment]
I am with @gnikonorov in this case. Although it might seem to have reasonable overlap, the intended concept is different. This plugin is first of all intended to cover re-runs in a broad range with minimal configuration. What you describe is a rather test case or fixture based dynamically adaptable way to modify a retry of a test case. In this case even the place to change the configuration at runtime is fundamentally different then before and might even require the use of different pytest-hooks or a totally different approach, for example as a fixture, which then can be modified/configured in the testcase, something like the [caplog fixture](https://docs.pytest.org/en/stable/logging.html?highlight=fixture#caplog-fixture).  As such I would disagree, that the best solution would share a lot technically in the end.

@gnikonorov In case you really want to write a plugin as an exercise, this might be a good opportunity. 

@xmo-odoo I will therefore close this issue and hope the discussion was helpful for you.

**Comment by gnikonorov** [comment]
Hi @xmo-odoo I’m going to start work on this in a separate repository in the coming days assuming no solution already exists. I’ll post a link to the project when I have something working. Is that ok with you?
