### ISSUE TITLE
_pytest.resultlog was removed in pytest 6.1.0

### ISSUE THREAD

**Issue by domdfcoding** [pytest-dev/pytest-rerunfailures#128]
`pytest-rerunfailures` imports `_pytest.resultlog` but the module was removed in https://github.com/pytest-dev/pytest/commit/ef946d557cc7b7f030805b94c1dbae51f39fcce4 .

As a result, it is no longer possible to use `pytest-rerunfailures` with pytest 6.1.0.

The suggested replacement is [pytest-reportlog](https://github.com/pytest-dev/pytest-reportlog).

**Comment by mdmintz** [comment]
This looks related to the issue that I just faced:

```
  File "/Users/michael/.virtualenvs/sbase7/lib/python3.7/site-packages/pytest_rerunfailures.py", line 7, in <module>
    from _pytest.resultlog import ResultLog
ModuleNotFoundError: No module named '_pytest.resultlog'
```

All pytest tests stop working if ``pytest-rerunfailures`` is installed.
