### ISSUE TITLE
Add support to rerun after all test cases are executed.

### ISSUE THREAD

**Issue by Phincle** [pytest-dev/pytest-rerunfailures#143]
when 1st round of test case execution, mark all failed cases.
then rerun the 2nd round.

it is helpful for working with pytest-xdist and Memory allocate error. 
usually if rerun as soon as an error is reported, memory is till full.
if reruns after 1st round, memory wil be free.

**Comment by icemac** [comment]
This behavior could be achieved running without this plug-in but with bare pytest using the `--lf` option to get a second round running only the failed tests.

**Comment by Phincle** [comment]
Thanks very much，when I run without the plugin, the option is really helpful.😀
However my project need xdist for parallel acceleration,  which caused Memory error.
