### ISSUE TITLE
Restore compatibility with pytest master.

### ISSUE THREAD

**Issue by sallner** [pytest-dev/pytest-rerunfailures#153]
With the refactoring of `SetupState` in `pytest` (https://github.com/pytest-dev/pytest/pull/8219) a regression was introduced to the solution of #144/#152. @bluetech as you added the change could you maybe suggest something to go along with the new master? It would probable be a good idea to add a changelog entry for other plugins to be prepared.

**Comment by bsipocz** [comment]
This probably can be closed as CI includes jobs with pytest's main branch.

**Comment by icemac** [comment]
@bsipocz You are right, I will close this issue.
