### ISSUE TITLE
Not compatible with asyncio

### ISSUE THREAD

**Issue by dvarrazzo** [pytest-dev/pytest-rerunfailures#154]
```
import pytest

@pytest.mark.asyncio
@pytest.mark.flaky
async def test_flaky_no_rety():
    assert False
```

Fails with "RuntimeError: Event loop is closed"

**Comment by yuvipanda** [comment]
I played around with ordering of the mark calls, but no effect.

**Comment by heliping** [comment]
also faced this problem, I used pyppeteer to test web UI, ther rerun don't work.
![image](https://user-images.githubusercontent.com/24326525/129501190-8649db1b-6347-41c5-8cfb-00e3187b006d.png)

**Comment by johny-b** [comment]
As a ugly workaround, something like this in my `conftest.py` seems to work:
```
class LoopThatIsNeverClosed(asyncio.AbstractEventLoop):
    """Just a loop, but if you try to use it after it was closed you use a fresh loop"""

    def __init__(self):
        self._loop = None

    def __getattribute__(self, name):
        if name == "_loop":
            return super().__getattribute__("_loop")
        if self._loop is None or self._loop._closed:
            self._loop = asyncio.new_event_loop()
        return getattr(self._loop, name)


@pytest.fixture
def event_loop():
    """This overrides `pytest.asyncio` fixture"""
    loop = LoopThatIsNeverClosed()
    yield loop
    loop.close()
```

But this might have some side effects I don't know about.

**Comment by Fleapse** [comment]
pytest-rerunfailures==10.2
![image](https://user-images.githubusercontent.com/51268198/156335053-3ec4cf6e-7964-4a68-b211-3bbdac4fae55.png)

**Comment by arg0d** [comment]
Some recent version of pytest-asyncio has fixed the issue. When using `pytest-asyncio ~= 0.18`, this error goes away. There is also an identical issue in `flaky` project https://github.com/box/flaky/issues/166

**Comment by seifertm** [comment]
Is this issue still relevant?
If so, is there a change needed on pytest-rerunfailure or in pytest-asyncio?

**Comment by dvarrazzo** [comment]
I have personally [replaced you with a shell script](https://github.com/psycopg/psycopg/blob/fcda5be26c2fb1cd1ac8fd1582a0af4705aed03c/tools/build/ci_test.sh#L24-L28) and moved on with life, but I assume someone might appreciate this to work.

**Comment by icemac** [comment]
According to @arg0d this issue is solved. So am closing it.
