### ISSUE TITLE
Failures are not recognized in request.session.testsfailed until after test teardown

### ISSUE THREAD

**Issue by duncanariey** [pytest-dev/pytest-rerunfailures#155]
I maintain a suite of Selenium tests that have functionality to take a screenshot of the browser state in the case a test fails. The screenshot method works by checking the state of request.session.testsfailed on test setup, and checking again during teardown, and determining if the state has changed between setup and teardown. If request.session.testsfailed has changed between setup and teardown, the currently executing test is determined to have failed, and a screenshot is taken before the browser is closed.

When running tests without rerunfailures, request.session.testsfailed is incremented as soon as a failure condition occurs, which is pre-teardown. Now that I am running the suite with rerunfailures, I see that request.session.testsfailed is only being incremented **after** the teardown of a failed test.

To illustrate the code, this is the simplified setup and teardown fixture I currently use in conftest.py:

```
@pytest.fixture
def browser():
    driver = Chrome(ChromeDriverManager().install())
    failed_before = request.session.testsfailed
    yield driver
    print(str(request.session.testsfailed))
    if request.session.testsfailed != failed_before:
        test_name = request.node.name
        take_screenshot(driver, test_name)
    driver.quit()
```

To illustrate when request.session.testsfailed is being incremented, this is the simplified reporting for a run of two tests I set to intentionally fail, with a flag of `--reruns 1` with the state of request.session.testsfailed being printed during the teardown of each test:

```
tests/test_homepage.py  
0
R 
0
F 
1
R 
1
F
```

As opposed to the output when running those tests without `--reruns 1`

```
tests/test_homepage.py  
F1
F2
```

Notice that in the former (rerunfailures) case, incrementation only happens following teardown, while in the latter (default) case, incrementation has already happened pre-teardown.

Hopefully this is a somewhat clear explanation. Happy to clarify further if there are any questions. Would very much appreciate any looking into this that you might be able to do!

**Comment by symonk** [comment]
seems a very long winded way of doing things to check the session, why not just check if each particular test has failed post-yield in a fixture and screenshot accordingly?

**Comment by duncanariey** [comment]
This worked, thank you!
