### ISSUE TITLE
reruns condition  evaluates not in real time

### ISSUE THREAD

**Issue by 15klli** [pytest-dev/pytest-rerunfailures#161]
* version: 10.0
* code 
```python
retryBool = True
@pytest.mark.flaky(condition=retryBool,reruns=2)
def test_demo():
    retryBool = False
    assert False
```

I found that if I set the mark like the above code, It can't stop retry when after the first run. It shows that the `condition` does not evaluate in real time  but  before the case was run. 

But I think  it's better if the condition evaluates in real time, because it let me able to control  the retry on runtime. For example, if  the number of  failed cases reaches  a certain number, then retry the following failed cases.

And the`@pytest.mark.skipif(condition="bool",reason="xxx")`  evaluates in real time.

**Comment by icemac** [comment]
To change the value of the global variable you have to declare it `global`, otherwise you create a new independent local variable in your test function:

```python
retryBool = True
@pytest.mark.flaky(condition=retryBool,reruns=2)
def test_demo():
    global retryBool
    retryBool = False
    assert False
```

See https://docs.python.org/3/reference/simple_stmts.html#grammar-token-global-stmt for details about `global`.

**Comment by 15klli** [comment]
Sorry, my Fault. I forgot to add global.  But after  declaring it  `global `, it also  doesn't work.

![image](https://user-images.githubusercontent.com/17797189/122542304-21a61300-d05d-11eb-99f2-1717bd017826.png)


And I  refactor this with my [PR](https://github.com/pytest-dev/pytest-rerunfailures/pull/162)
