### ISSUE TITLE
Rerun does not work with pytest-forked

### ISSUE THREAD

**Issue by suhjohn** [pytest-dev/pytest-rerunfailures#163]
pytest                             6.2.2
pytest-forked                      1.2.0
pytest-rerunfailures               10.0
pytest-xdist                       2.3.0

Given the following versions, running `pytest -n 2 --reruns 2 --forked` does not trigger reruns. Without --forked it does. Is this intended?

**Comment by icemac** [comment]
@suhjohn Could you please provide a minimal working example to reproduce the issue?

**Comment by icemac** [comment]
I am closing this old issue. Feel free to re-open it if there are any news about the topic.
