### ISSUE TITLE
Plugin fails with [XPASS(strict)]

### ISSUE THREAD

**Issue by Mal-lab** [pytest-dev/pytest-rerunfailures#175]
Hello!
I have the following problem:
In my project, I need to use the `xfail = strict` option. I run rerun-failures with the `--only-rerun RuntimeError `parameter.
If my test passes unexpectedly, I get an error like:

> some_path/python3.8/site-packages/pytest_rerunfailures.py", line 287, in _should_hard_fail_on_error
> INTERNALERROR>     if re.search(rerun_regex, report.longrepr.reprcrash.message):
> `AttributeError: 'str' object has no attribute 'reprcrash'`. 

Is there an easy way to avoid this? Thanks in advance!
Possible rough solution to the problem:

>     for rerun_regex in rerun_errors:
>         try:
>             if re.search(rerun_regex, report.longrepr.reprcrash.message):
>                 return False
>         except AttributeError:
>             if re.search(rerun_regex, report.longreprtext):
>                 return False

**Comment by icemac** [comment]
Thank you for reporting this issue. A PR is welcome.

**Comment by icemac** [comment]
Fixed by #186.
