### ISSUE TITLE
need support for '--rerun-other-than' option

### ISSUE THREAD

**Issue by dheepan2** [pytest-dev/pytest-rerunfailures#179]
It would be great to have an option to rerun other than a particular error,
For example let pytests fail if only AssertionError, and continue the number of reruns for any other Errors or Exceptions like (OSError, Memory issue, Connection issues I want a rerun option.)

We currently have '--only-rerun' similarly can we have '--rerun-other-than' option too.

**Comment by icemac** [comment]
@dheepan2 Is this issue now fixed by merging #180?

**Comment by dheepan2** [comment]
yes, the issue is fixed by merging #180  We can close this issue.
