### ISSUE TITLE
ENH: rerun tests at the end of the test run

### ISSUE THREAD

**Issue by bsipocz** [pytest-dev/pytest-rerunfailures#193]
I would like to use `rerunfailures` in a library that has a lot of tests accessing online services. The whole test suite runs quite a long time, and some of the servers may be rather flaky at times, so would like to get everything run first and rerun the failing ones at the end of all tests, rather than right after the individual failures.

As far as I saw in the documentation this mode is not yet supported, would you consider it?

**Comment by bsipocz** [comment]
I found a workaround outside of this plugin and I suppose others may interested in it, too:

- run a second pytest command with the ``--last-failed``, it will pick up only the failed tests and rerun them. That adds a sufficiently long delay time to filter out the flaky services my tests may run into.

**Comment by icemac** [comment]
@bsipocz Congratulations you found a solution which does not involve writing new code.
I'd prefer the approach you found over a new feature in this project. So closing this feature request.
