### ISSUE TITLE
pytest argument --rerun-except  is not recognized

### ISSUE THREAD

**Issue by azazrehman** [pytest-dev/pytest-rerunfailures#197]
I am executing the following command and it's working fine.
`pytest --reruns 5  /<my_test_file>py`
But when I add the flag --rerun-except its not recognize the flag
`pytest --reruns 5 --rerun-except AssertionError /<test_file_path>.py`

Following error received 
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --rerun-except
  inifile: None
  rootdir: /<my_root_directory>

**Comment by icemac** [comment]
This probably occurs because `--rerun-except` was added in a version which is not released yet.

**Comment by icemac** [comment]
I just released https://pypi.org/project/pytest-rerunfailures/10.3/ containing this feature.
