### ISSUE TITLE
Support `--only-rerun` in a `@pytest.mark.flaky` decorator

### ISSUE THREAD

**Issue by AIGeneratedUsername** [pytest-dev/pytest-rerunfailures#215]
Extend https://github.com/pytest-dev/pytest-rerunfailures/issues/101 to support the same functionality in `pytest.mark`.

Example: `@pytest.mark.flaky(only_rerun=MyException)`.

**Comment by icemac** [comment]
Hi @AIGeneratedUsername, thats an interesting idea. A PR is welcome.
