### ISSUE TITLE
rerun doesnt work in gitlab pipeline

### ISSUE THREAD

**Issue by wonder19** [pytest-dev/pytest-rerunfailures#216]
hello! firstly, thank you for your product! its really nice in use<3
but i've came accross some strange situation
everything works perfect locally on my mac by sh script
 pytest --reruns 5 --reruns-delay 5 --tb=line ./tests -m common

also it works by typing command in terminal

but when i start gitlab pipelene rerun doesnt work
if test failed run completed
i dont use any flaky marks or other plugins

on my image i have linux
all requirements install Successfully 
use pytest_rerunfailures-11.1.2
also ive tried sh script and gitlab yml script

tests_rerun:
  extends: .before_script_template
  stage: test
  tags:
    - docker-ui-tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual
    - if: '$CI_PIPELINE_SOURCE == "push"'
  script:
    - pytest --reruns 5 --reruns-delay 5 --tb=line ./tests -m common

**Comment by icemac** [comment]
Hi @wonder19, is there a traceback you can share?
Your description is too vage to draw any conclusions from it to recognize what could cause your problem.

**Comment by wonder19** [comment]
Hi @icemac 
unfortunately, my real gitlab repo has sensitive data, but i've tried to create another just to make sure it has the same problem but everything works pretty fine 
so, is it enough to send part of my real repo traceback on image?
![image](https://user-images.githubusercontent.com/62057940/236163140-3b9299df-873c-4eeb-8314-32055d93e1bd.png)

**Comment by icemac** [comment]
According to your screenshot you are using the plug-ins `pytest-rerunfailures` and `flaky` at the same time. Both define `@pytest.mark.flaky`. I would expect this does not go well.
So you should decide for one of them. This possibly requires changing the parameters for `@pytest.mark.flaky` to the requirements of the chosen plug-in.

**Comment by wonder19** [comment]
@icemac  Hello!
may be any other suggestions? :,(

**Comment by icemac** [comment]
I cannot imagine how `pytest-rerunfailures` and `flaky` can run fine together locally. They define the same `pytest.mark` but with different parameters. Decide for one of them to see if it runs on Gitlab.

**Comment by icemac** [comment]
See also #217.
