### ISSUE TITLE
Is this project unmaintained

### ISSUE THREAD

**Issue by jwg4** [pytest-dev/pytest-rerunfailures#22]
Is it still the case that this project is unmaintained?

I haven't seen any packages with similiar functionality for rerunning flaky tests as this for Python. Is there something else that anyone would recommend, or is this project the best place to start?

**Comment by klrmn** [comment]
I was the original creator of this project, but I thought the gocept team
was planning to maintain it.

-Leah

**Comment by davehunt** [comment]
I just submitted a pull request, with a few enhancements. Hopefully they'll be merged and we'll see a new release. Otherwise, it might be worth seeing if we can transfer this to https://github.com/pytest-dev.

**Comment by nicoddemus** [comment]
:+1: about moving to the pytest-dev organization. One of the reasons we created the organization was to embrace plugins whose maintainers no longer wish to support the project (as stated in this repo's README).

Moving this project to pytest-dev organization would be a first step, the next would be to look for an official maintainer. @davehunt seems interested and knows his way around the code from the look of #23, perhaps you could be a candidate for that? :wink:

**Comment by davehunt** [comment]
Perhaps we could get a comment from @gocept? As for being the official maintainer, if this was relocated to pytest-dev I'd be okay with a caretaker role, but I personally feel that flaky tests should be fixed or removed. I'm therefore not an advocate for the features of this plugin. :smile:

**Comment by nicoddemus** [comment]
> I'm therefore not an advocate for the features of this plugin. :smile:

Certainly. Ideally they should have a ticket associated with them and fixed ASAP. :smile:

**Comment by davehunt** [comment]
@florianpilz I see you've commented on other issues. Would you mind adding your thoughts here and in pull #23?

**Comment by florianpilz** [comment]
Thanks for notifying me. Yes, gocept is still the maintainer of this package. Until this Pull Request came, there was not much interest in existing issues, so there was nothing to do. Sorry that we overlooked your Pull Request, we are still working on a solution to increase visibility of our Open Source projects.

However, we would be fine to transfer this package to `pytest-dev`. We are still interested in maintaining it, though.

**Comment by nicoddemus** [comment]
@florianpilz could you send an email to `pytest-dev@python.org` formally requesting it to be moved to `pytest-dev` then?

**Comment by florianpilz** [comment]
@nicoddemus: I'm currently on vacation. I will do so next year.

**Comment by nicoddemus** [comment]
No problem, have a nice vacation! :smile:

**Comment by davehunt** [comment]
@florianpilz I hope you had a great vacation. Would you have time to look over pull #23 and perhaps release a new version?

**Comment by florianpilz** [comment]
@davehunt Hi, I glanced over it last week. Huge change! I need some time to consume the changes for QA. I will try to squeeze this into my usual payload, but chances are that the release must wait till first week in February (we have repeating "clean-up" weeks).

**Comment by florianpilz** [comment]
Hi @davehunt, today is the day! I have big troubles to review your changes, since you mixed renames with changes. Therefore I will repeat your changes on a branch, but separate the rename part into a separate commit (and maybe split some more changes into commits). Please use smaller commits in the future. ;)

**Comment by davehunt** [comment]
Let's close this issue, as the project is being maintained, and move conversation of my pull request over to the pull request. :)
