### ISSUE TITLE
Can you identify if a particular is a re-run or not?

### ISSUE THREAD

**Issue by tking16** [pytest-dev/pytest-rerunfailures#231]
Hi, I have a quick general question. I'd like to start a screen recording only when a test has failed and has is on a rerun. Is there some way to identify that a test is being reran? I tried `request.config.option.lf` but it just returns `false` whether a test is being run for the first time or not!

**Comment by icemac** [comment]
I do not know about a the possibility to identify that a re-run is currently in progress.
There is `item.execution_count`, see https://github.com/pytest-dev/pytest-rerunfailures/blob/c6ff082a36e927b27fd8418737f49e116d03a22a/pytest_rerunfailures.py#L606C1-L607C1 But you are probably not able to access `item` during a test run.

**Comment by The-Compiler** [comment]
> But you are probably not able to access `item` during a test run.

You can, via the [`request` fixture](https://docs.pytest.org/en/7.1.x/reference/reference.html#std-fixture-request) and `request.node` - e.g.:

```python
def test_rerun(request):
    if request.node.execution_count == 1:
        1/0
```

results in:

```
test_x.py::test_rerun RERUN
test_x.py::test_rerun PASSED
```

**Comment by icemac** [comment]
Thank you @The-Compiler for sharing your knowledge. I assume the question as answered and will set the issue to resolved.
