### ISSUE TITLE
Backward Compatibility

### ISSUE THREAD

**Issue by florianpilz** [pytest-dev/pytest-rerunfailures#27]
The plugin was largely rewritten by @davehunt in #23. However we now use `get_marker`, thus require at least `pytest >= 2.4.2`. What do you think about backward compatibility? Is it OK to drop support for older versions of pytest?

**Comment by florianpilz** [comment]
@davehunt The `setup.py` currently states that `pytest >= 2.7.3` is required. Did you just choose any current version or did you depend on features introduced in `2.7.3` for your rewrite?

**Comment by davehunt** [comment]
I generally work against the latest point releases of the current and previous major releases. It may be that there's still support for pytest 2.4.x -> 2.6.x. It would be easy to add these to `tox.ini` to check compatibility.

**Comment by The-Compiler** [comment]
pytest 2.4 is now nearly 2.5 years old - if someone is still using that, they won't have issues with sticking to an older rerunfailures release either :wink:

For my plugins, I aim for 2.7/2.8 compatibility, and might drop 2.7 when 2.9 comes out. Not sure how much 2.4/2.5/2.6 compatibility is still worth, no idea how many people still use that but want to update their plugins.

**Comment by davehunt** [comment]
In hindsight I think I would set the compatibility to `>= 2.7.0` rather than force users to be on the latest point release, unless there's a good reason to do so.

**Comment by florianpilz** [comment]
Since tests run successfully with pytest `2.4.2` I decided to use this version in the `setup.py`. I also made sure tests are run via tox and Travis. I also documented the compatibility in the README, as well as issues I had setting up Python 3.2
