### ISSUE TITLE
The teardown does not execute properly for session level fixture when we use `--reruns` (from `pytest-rerunfailures`)

### ISSUE THREAD

**Issue by komalc9** [pytest-dev/pytest-rerunfailures#272]
When you will run the "test_example_fixture" test, You will observe that the **teardown** is never printed in console. This is restricting the clean up in my project.

**NOTE: It happens only when we use rerun failed tests.**

```python
import pytest

@pytest.fixture(scope="session")
def example_fixture():
    print("\nSetup")
    yield
    **print("Teardown")**

@pytest.mark.flaky(reruns=1)
def test_example_fixture(example_fixture):
    assert 0
```

**Comment by icemac** [comment]
Pytest 8.2 is not yet supported, see #267. So closing this issue in favor of that one.
