### ISSUE TITLE
Not compatible with resultslog

### ISSUE THREAD

**Issue by Kanguros** [pytest-dev/pytest-rerunfailures#28]
Hi,

The plugin is not compatible with the resultslog module from pytest.

By default the resultslog will not be created. To turn on this feature you need to set the `--resultlog` or `--result-log` pytest command line parameter. If we have a failing test and run pytest like so:

`$ pytest --result-log=pytest.log --reruns=3`

we will get the following error:

`...`
`INTERNALERROR>     res = hook_impl.function(*args)`
`INTERNALERROR>   File "c:\users\eostr\envs\pytest\lib\site-packages\_pytest\resultlog.py", line 86, in pytest_runtest_logreport`
`INTERNALERROR>     self.log_outcome(report, code, longrepr)`
`INTERNALERROR> UnboundLocalError: local variable 'longrepr' referenced before assignment`

This problem is cause because when a test fails for the first time (and not last time) line 86 is executed. The value of `report` will be set to `rerun`. In `pytest.pytest_runtest_logreport` there are a bunch of check that set the value of `longrepr` based on `report`. Since `rerun` is not valid value, `longrepr` does not get set.

Cheers,
Edgar

**Comment by florianpilz** [comment]
Can you provide a test or even better a Pull Request to fix this issue? I will have no time for this issue during the following weeks.

**Comment by klrmn** [comment]
or a PR to the README to document the incompatibility. when I wrote it, I
never expected it to be able to work with *every* pytest plugin, i just
knew that xdist was really important to work with.
