### ISSUE TITLE
Tests stop with --exitfirst, even when rerun successfully

### ISSUE THREAD

**Issue by florianpilz** [pytest-dev/pytest-rerunfailures#32]
There currently is a problem with `--exitfirst`. In my understanding, the tests should stop when for the first time a test failed **after rerunning it n times**. This does happen, but in contrast the tests will also stop when a test failed and succeeded during a rerun.

So in other words, currently the test suite will be run normally and stops at first failure, but this failure will be run n times. However, I would expect the test suite to continue, when a failing test could be rerun successfully.

Part of the solution would be to reset the `--exitfirst` counter (internally it's implemented with `--maxfail num` with `num = 1` which stops after `num` failures).

**Comment by EdgarOstrowski** [comment]
Hi,

I tried writing a test that exposes the problem. Here it is:
```
def test_rerun_exitfirst(testdir):
    testdir.makepyfile("""
    results = [True, False]
    
    def test_flaky():
        assert results.pop()
        
    def test_passing():
        assert True
    """)

    result = testdir.runpytest('--reruns', '2', '-x')
    assert_outcomes(result, failed=0, rerun=1, passed=2)
```
If I understand the described problem this test should fail. But it doesn't it passes. So what am missing here?

**Comment by icemac** [comment]
I am closing this old issue. Feel free to re-open it if there are any news about the topic.
