### ISSUE TITLE
Don't rerun skipped tests

### ISSUE THREAD

**Issue by tlotze** [pytest-dev/pytest-rerunfailures#33]
Skipped tests appear to be rerun, and thereby skipped multiple times.

**Comment by davehunt** [comment]
@tlotze could you provide an example? How are you skipping your tests? This certainly was an issue (see https://github.com/pytest-dev/pytest-rerunfailures/issues/13), but I believe it was addressed in v1.0.0.

**Comment by tlotze** [comment]
In fact, I cannot reproduce the behaviour using current pytest-rerunfailures. I'll close the ticket; sorry about the noise.

**Comment by tlotze** [comment]
In fact, I cannot reproduce the behaviour using current pytest-rerunfailures. I'll close the ticket; sorry about the noise.
