### ISSUE TITLE
Command line switch to disable?

### ISSUE THREAD

**Issue by rouge8** [pytest-dev/pytest-rerunfailures#34]
One feature that I often find myself wishing for is a command line switch to disable reruns entirely, even for tests marked with `@pytest.flaky(reruns=N)`. This would be useful when rewriting/updating tests without commenting/uncommenting the `@pytest.flaky` decorator.

**Comment by davehunt** [comment]
You should be able to disable the plugin using pytest's `-p no:rerunfailures` command line option.

**Comment by rouge8** [comment]
Hmm. That breaks if you also use `--strict` (e.g. through `pytest.ini`), but that's good enough for me.

**Comment by sallner** [comment]
I also encountered a similar problem with other plugins. If there is a flag like `--rerun 3` in a `pytest.ini` or in a `tox.ini` then I found no way to switch off the plugin. `-p no:rerunfailures` will cause the following error `py.test: error: unrecognized arguments: --rerun`. Has there been a solution for other plugins to cope with that?

**Comment by The-Compiler** [comment]
I've had the same issue before as well...  Is there something we could add for this scenario from the pytest side?

I guess there could be a `-p ignore:rerunfailures` or so which runs `pytest_addoption` (to add the commandline switches) but no other hooks. Then again depending what kind of stuff plugins do there (or at import time) this might lead to weird effects... So maybe this is better solved individually per-plugin  indeed.

**Comment by astraw38** [comment]
IMO, it's a non-issue that disabling a plugin also disables it's command line options. That'd be expected, and changing it would just make it more confusing. Instead, don't use plugin options in your ini files if you're also going to need to disable them at a later date.

**Comment by florianpilz** [comment]
I agree that `-p no:rerunfailures` should be sufficient. Disabling reruns should not occur on a daily basis, rather to check if a global bugfix squished most of the brittle test failures. Removing the rerun option from a single `INI` file to avoid `unrecognized arguments` sounds good to me.
