### ISSUE TITLE
Default to 1 rerun if number of reruns not specified

### ISSUE THREAD

**Issue by lexrj** [pytest-dev/pytest-rerunfailures#38]
Instead of throwing an error when the number of reruns aren't specified, can it have a default parameter of 1?

**Comment by florianpilz** [comment]
Hm, that would certainly be possible. But if you are using a `pytest.ini`, that shouldn't be an issue, right?

**Comment by florianpilz** [comment]
@lexrj Sorry, I did not see your response. *That* is actually very simple and I like your proposal. Since @sallner is taking over maintenance of the package: @sallner can you please implement the proposal?

**Comment by sallner** [comment]
This issue was solved with #41.
