### ISSUE TITLE
Add wait time

### ISSUE THREAD

**Issue by mblaschke** [pytest-dev/pytest-rerunfailures#42]
For testing with infratest it would be nice to add a delay for reruns (in seconds)

**Comment by icemac** [comment]
Nice idea. Pull requests are welcome.

**Comment by Kanguros** [comment]
This look like something that I could give a go at. @icemac can you please assign this to me?

**Comment by icemac** [comment]
@Kanguros Sorry for the long delay but I am not able to assign this issue to you: Your name does not show up in the Assignees list. 😱 I am not an administrator of the project so I am not able to look into the configuration. 
@sallner Are you able to assign this issue to @Kanguros?

**Comment by sallner** [comment]
@icemac @Kanguros it seems that I can only assign members of the pytest organization to an issue. Have you gotten any further with the actual problem? Then we can have a look at it.

**Comment by sallner** [comment]
@Kanguros What is the status of your contribution? Do you need help with anything?

**Comment by Kanguros** [comment]
@sallner I finally found some time to work on this. I'll try to get this finished in a couple of days. I already have the command line argument working. Now going to try to add to marker.

**Comment by sallner** [comment]
@Kanguros Thank you again for working on this feature. 

@mblaschke If you are still interested, I just released a 4.0 including this feature on pypi.
