### ISSUE TITLE
Add optiontional "minimum number of passes" to consider a pass

### ISSUE THREAD

**Issue by lexrj** [pytest-dev/pytest-rerunfailures#43]
Currently rerunning a test n times is allowed, but as long as it passes once, the test is considered passed. It would be helpful to have a minimum number of passes required for the test to be considered a pass, for more nuanced pass rates.

Example: I know something fails 33% of the time, so I want to run it four times and make sure it passes at least twice, otherwise I should look into it.

**Comment by icemac** [comment]
This seems to be an interesting idea. A pull request is welcome.

**Comment by kousu** [comment]
For inspiration, [flaky](https://github.com/box/flaky)'s API for this looks like:

```
@flaky(max_runs=3, min_passes=2)
```

**Comment by gnikonorov** [comment]
Hey @icemac do you mind if I grab this one too?

**Comment by icemac** [comment]
@gnikonorov Feel free to tackle this one, too.

**Comment by icemac** [comment]
I am closing this old issue. Feel free to re-open it if there are any news about the topic.
