### ISSUE TITLE
Using pytest-rerunfailures causes --boxed flag for pytest-xdist to not be set.

### ISSUE THREAD

**Issue by jrbenny35** [pytest-dev/pytest-rerunfailures#44]
As the title says, installing this addon seems to cause xdist to ignore the ```--boxed``` flag.

```pytest -n 4 --boxed --driver Firefox```
This runs as 4 but not boxed. I don't know if this is a rerunfailures issue or an xdist issue.

**Comment by icemac** [comment]
I never used `xdist` before. Do you have an example project where this behaviour can be studied?

**Comment by sallner** [comment]
@jrbenny35 Is this still an issue for you? Otherwise I will close this issue.

**Comment by jrbenny35** [comment]
> 
> 
> @jrbenny35 Is this still an issue for you? Otherwise I will close this issue.

Hey, I haven't ran into this again, if I do I can reopen it. Thanks!
