### ISSUE TITLE
Update supported versions of pytest and Python

### ISSUE THREAD

**Issue by icemac** [pytest-dev/pytest-rerunfailures#49]
Drop support for
  - PYTEST=2.4.2
  - PYTEST=2.5.2
  - Python 2.6

Add Support for
  - PYTEST=3.0.7
  - PYTEST=3.1.2
  - Python 3.6

**Comment by bcfjohns** [comment]
Can you clarify what needs to be done to add support for pytest 3.1.2 and python 3.6? I did a simple test with python 3.6.1 and pytest 3.1.0 and it seemed to work fine. Planning to use this plug-in on a large project and I want to nail down the package versions we're going to start with.

**Comment by The-Compiler** [comment]
I'm guessing it's just not officially tested? FWIW I'm using it fine with Python 3.4-3.6 and pytest 3.2.0.

**Comment by icemac** [comment]
Let's see what TravisCI finds out in #52.

**Comment by icemac** [comment]
@bcfjohns The freshly released version 3.0 of this package now officially supports Python 3.6 and purest 3.1.3.
