### ISSUE TITLE
Ignore failed runs

### ISSUE THREAD

**Issue by rutyruty** [pytest-dev/pytest-rerunfailures#50]
We are using jenkins.
When running with pytest-rerunfailures, the build is marked as failed when there's one failure.
====================== 1 failed, 3 passed in 2.90 seconds ======================
Build step 'Execute shell' marked build as failure
Finished: FAILURE
Is it possible not to report the failed runs if there's at least one successful run. Only if all runs failed after <num reruns> will the test end with failure.

**Comment by sallner** [comment]
Hi @rutyruty,

A typical output of a jenkins run of a larger project of ours with occasional reruns looks like this:
`======== 3391 passed, 35 skipped, 8 xfailed, 2 rerun in 1777.08 seconds ========`

I am afraid there might be a configuration error or some incompatibility on specific versions. Could you please provide more information about your system, for example from the beginning of the test session? Maybe also the actual call to pytest and the content of `pytest.ini`?

**Comment by rutyruty** [comment]
Hi,

This is the complete test session:

============================= test session starts ==============================
platform linux2 -- Python 2.7.5, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /var/Nightswatch, inifile:
/usr/lib64/python2.7/site-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)
collected 4 items

../var/Nightswatch/CI_loops/CI_loop25/test_retry.py 1
.2
.3
F4
.

-------------- generated xml file: /tmp/test_retry.py_150.181.xml --------------
=================================== FAILURES ===================================
__________________ TestIngestCorruptVodFiles.test_example[3] ___________________

self = <CI_loops.CI_loop25.test_retry.TestIngestCorruptVodFiles object at 0x54e06d0>
b = 3

    @pytest.mark.parametrize('b', [1, 2, 3, 4])
    @pytest.mark.flaky(reruns=5)
    def test_example(self, b):
        print b
        c = 100
>       assert c % b == 0, 'fail'
E       AssertionError: fail
E       assert (100 % 3) == 0

/var/Nightswatch/CI_loops/CI_loop25/test_retry.py:21: AssertionError
====================== 1 failed, 3 passed in 2.92 seconds ======================
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by davehunt** [comment]
@rutyruty it doesn't look like pytest-rerunfailures is installed. Your test session header should include something like "plugins: rerunfailures-2.2". You could check what packages are installed by running `pip list`. You could also run your tests with `--strict` which would cause collection error such as `AttributeError: 'flaky' not a registered marker` if your tests use an unregistered marker.

**Comment by rutyruty** [comment]
Hi @davehunt 
Running pip list|grep rerunfailures on my env shows "pytest-rerunfailures (2.2)"
Will try to see if '--strict' will do the job. Thanks.

**Comment by sallner** [comment]
@rutyruty it really seems like pytest-rerunfailures is not loaded. It happened to me once, that I called a pytest outside from my venv, so that the packages installed in the venv did not get loaded. Could you maybe check for this?

**Comment by sallner** [comment]
@rutyruty could you give us an update on this matter? If you do not have any comments or questions on that, I would like to close this issue soon.

**Comment by sallner** [comment]
As there is no more reaction from @rutyruty, I close this issue
