### ISSUE TITLE
support invert case "rerunpassed"

### ISSUE THREAD

**Issue by dirk-thomas** [pytest-dev/pytest-rerunfailures#54]
Would it be in the scope of this plugin to support the invert case "rerunpassed" which reruns passed tests up to N times to ensure that they are not flaky?

I understand that this would be a little "against" the name of the plugin but I assume beside another command line options almost all of the logic will be the same except the condition deciding if the test needs to be retriggered.

I would be happy to provide a pull request if the feature is desired and a consensus on the design is reached. The alternative would be "duplicating" this plugin and naming it `pytest-rerunpassed` but that would imply a lot of duplicate effort from then on.

**Comment by davehunt** [comment]
@dirk-thomas check out https://github.com/pytest-dev/pytest-repeat

**Comment by dirk-thomas** [comment]
I am still new to pytest and the names of the plugins seem to be always different from what I am searching for :wink: Thank you for the pointer. That plugin will do exactly what I need.
