### ISSUE TITLE
rerun failures at session end instead of rerunning instantly

### ISSUE THREAD

**Issue by mulawamichal** [pytest-dev/pytest-rerunfailures#71]
hi,

would it be possible to eg. introduce a new option in the marker than if set would somehow collect failed tests in a list,and rerun that list at end of test session? I tried to achieve something like this myself, by simply 

    request.session.items.append(request.node)

but it doesn't work with xdist, as it collects the test queue at session start and distributes it to the slave workers.

**Comment by sallner** [comment]
As @RonnyPfannschmidt mentioned in [pytest-xdist#355](https://github.com/pytest-dev/pytest-xdist/issues/355) that it not possible. 

If you need that so urgently, then it might also be an approach to write only those in the lastfailed cache and rerun them immediately afterwards. But I can not guarantee, that this would work, in particular with `pytest-xdist` as I have very little experience with it. 

If you do not have any other questions, I would close this issue.
