### ISSUE TITLE
The 4.2 version bug

### ISSUE THREAD

**Issue by Yanci516** [pytest-dev/pytest-rerunfailures#72]
In version 4.2, when a file has multiple use cases, the first use case fails and retries without tearDownClass execution and runs setUpClass directly; in version 4.1, this situation does not execute setUpClass

**Comment by sallner** [comment]
@YancyGo could you please provide a minimal example so that I can reproduce this behaviour?

**Comment by sallner** [comment]
@YancyGo Does this issue still persist? In that case could you please provide a minimal example? Otherwise I will close this issue soon.

**Comment by sallner** [comment]
I close this bug due to a lack of feedback.
