### ISSUE TITLE
Lack of rerun attribute on report since 4.2 version

### ISSUE THREAD

**Issue by RibeiroAna** [pytest-dev/pytest-rerunfailures#77]
Some Pytest-HTML tests were failing since October and I realised that it was mainly because of that specific line: 

`test_index = hasattr(report, 'rerun') and report.rerun + 1 or 0`

The problem is that until version 4.1, the report had a rerun attribute, but for some reason it was taken off in version 4.2.  I wish that it could come back.

**Comment by RibeiroAna** [comment]
@sallner before closing the issue, just one question: when do you intend to release version 6?

**Comment by sallner** [comment]
@RibeiroAna I will add some maintenance stuff and should cut a release later today.

**Comment by sallner** [comment]
The new release including a fix for this regression can be found here https://pypi.org/project/pytest-rerunfailures/6.0/
