### ISSUE TITLE
Add Flake8 verification

### ISSUE THREAD

**Issue by RibeiroAna** [pytest-dev/pytest-rerunfailures#80]
Hi, when I was writing my last contribution I realised that rerunfailures doesn't have Flake8 verifications. I wish I could add that (unless you don't have it for some other reason)

**Comment by sallner** [comment]
Hi @RibeiroAna , thanks for that idea and I would welcome a PR very much. It was mainly, that I did not find the motivation lately. Actually, I would also like to try out `black` for general formatting. But I would prefere that as separate PR maybe in the beginning?

I will just keep a list here with potential maintenance stuff to remind myself and for other to join in. 

- [ ] black as default formatter, travis check for that. Needs some documentation for contributing.
- [ ] Flake8 which complies with the output black generates.
- [ ] Add coverage and activate coveralls.

**Comment by NathanUrwin** [comment]
I would recommend using pylint too. The best case scenario is using pylint and flake8 together, since they both will catch things the other doesn't. Just my two cents!

**Comment by gnikonorov** [comment]
Grabbing this as per https://github.com/pytest-dev/pytest-rerunfailures/pull/115#discussion_r457497214

**Comment by gnikonorov** [comment]
How do we feel about making this repo mirror what pytest is doing and using precommit to enforce this as well

Also, we could use [black](https://pypi.org/project/black/) for code formatting like pytest does
