### ISSUE TITLE
Add `reason` argument to @pytest.mark.flaky, similar to @pytest.mark.xfail

### ISSUE THREAD

**Issue by arthursoprana** [pytest-dev/pytest-rerunfailures#96]
Add `reason` argument to @pytest.mark.flaky, similar to @pytest.mark.xfail. This may be useful for associating the `@pytest.mark.flaky` decorator to an issue on github, JIRA or any other issue tracker.

**Comment by sallner** [comment]
@arthursoprana What is the reason you closed the issue again that fast. I actually quite like this idea. Would you like to provide a PR on that?

**Comment by arthursoprana** [comment]
Hm sorry, I should have commented something before closing. I’ve closed because it is already possible to do so.
