### ISSUE TITLE
Integrate with JUnit

### ISSUE THREAD

**Issue by epage** [pytest-dev/pytest-rerunfailures#97]
Use case: I want to analyze my test results over time to find and address flaky tests.  My test results are uploaded to a data analysis tool like Kibana using JUnit.

Problem: Pytest's JUnit support does not capture retries.  Only the last test run is recorded and no properties are added that indicate retries.

Example JUnit:
```xml
<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="epage-2328.local" name="pytest" skipped="0" tests="1" time="0.057" timestamp="2019-11-07T08:24:07.922770"><testcase classname="tests.test_foo" file="tests/test_foo.py" line="2" name="test_foo" time="0.003"><failure message="assert False">@pytest.mark.flaky(reruns=5)
    def test_foo():
&gt;       assert False
E       assert False

tests/test_foo.py:5: AssertionError</failure></testcase></testsuite></testsuites>
```

Suggested fix: Report `execution_count` using the `record_property` fixture so we know how many attempts were made.

Workarounds:
- `--result-log` (deprecated): Create a parser for `result-log` and merge in its results
- Wait until pytest 5.3 is release and use the new [`--report-log`](https://github.com/pytest-dev/pytest/pull/5980)

**Comment by sallner** [comment]
@epage Thank you for your idea. There has been some tradition on JUnit issues around pytest mainly because the XML-format, which is used by different aggregators may vary (Jenkins, Kibana etc.)

When I read one of the most common referenced specification on [JUnit-XML](https://llg.cubic.org/docs/junit/), there seems to be not much space to indicate the retry count or even that  the test was retried. Where would you actually like to report the counts?

**Comment by epage** [comment]
Hmm, I thought `<properties>` was supported in `testcase` but that only lists it in `testsuite`.

However, `pytest` supports adding `<properties>` to `testcase`
https://github.com/pytest-dev/pytest/blob/master/src/_pytest/junitxml.py#L149

So I'm unsure whether it is a good idea or not to use it.

**Comment by gaucheph** [comment]
wouldn't it make sense to have 2 results for the same test in this case? since it was run twice?

**Comment by sallner** [comment]
@gaucheph I do not think, that it a good idea to have two testcases with the same name etc. as it would increase the number of testcases only in the case of a rerun. This would in turn lead to an unstable number of testcases in different runs without code change. That sounds not right for me.

**Comment by sallner** [comment]
I am still not sure, whether we should add more tests in the junit.xml. As pytest 5.3 is now out for a long time, there seems to be a workaround for this problem. I will close this issue for now.
